messages:
  broadcast_all_start: |
    &a{player} &7has boosted &6everyone &7with &e{boost} &7for &b{time}&7!
    &7Make sure to thank them!
  broadcast_single_start: "&a{player} &7boosted &e{target} &7with &6{boost} &7for &b{time}&7!"

boosts:
  vip:
    group: "vip"
    global_start_message: ""
    global_end_message: "&c%player%'s &e%boost_name% &chas ended."
    sound:
      name: "BLOCK_NOTE_BLOCK_PLING"
      volume: 1.0
      pitch: 1.0
    commands:
      - start: "say Enjoy your VIP, %player%!"
        end: "say %player%'s VIP is over."
  fly:
    group: "fly"
    global_start_message: ""
    global_end_message: "&c%player%'s &e%boost_name% &chas ended."
    sound:
      name: "ENTITY_EXPERIENCE_ORB_PICKUP"
      volume: 1.0
      pitch: 1.0
    commands:
      - start: "lp user %player_uuid% permission set essentials.fly true"
        end: "lp user %player_uuid% permission unset essentials.fly"
