name: Boosted
main: com.depressy.boosted.BoostedPlugin
version: 1.0.1
softdepend: [LuckPerms]
api-version: '1.21'
authors: [Depressy]
description: Temporary permissions and boosters with LuckPerms + custom commands
website: https://example.com/boosted

commands:
  boost:
    description: Start a configured boost for a player or players for a duration
    usage: /boost <player|@s|@a|@all> <boostName> <duration>|reload
    permission: boosted.admin
  unboost:
    description: End all active instances of the named boost early
    usage: /unboost <boostName>
    permission: boosted.admin
  boostlist:
    description: List active boosts and remaining time (grouped). Use /boostlist <name> to expand.
    usage: /boostlist [name]
    permission: boosted.admin

permissions:
  boosted.admin:
    description: Allows using Boosted admin commands
    default: op
  boosted.bypass:
    description: Users with this permission are never targeted by boosts
    default: false
