name: Boosted
main: com.depressy.boosted.BoostedPlugin
version: 1.0.5
api-version: '1.20'
author: depressy
commands:
  boost:
    description: Apply a boost
    usage: /boost <@all|player> <boostName> <duration>
    permission: boosted.boost
  unboost:
    description: End boosts
    usage: /unboost <boostName|all>
    permission: boosted.unboost
  boostlist:
    description: List active boosts
    usage: /boostlist
    permission: boosted.list
permissions:
  boosted.boost: { default: op }
  boosted.unboost: { default: op }
  boosted.list: { default: op }
  boosted.bypass: { default: false }
